import { Platform, StyleSheet } from 'react-native';
import { spacing, borderRadius } from './_theme-constants';
import { tabColors } from './_tab-theme';

export const scanPalette = tabColors;

export const styles = StyleSheet.create({
  fullFill: StyleSheet.absoluteFillObject,
  container: {
    flex: 1,
    backgroundColor: scanPalette.background,
  },
  header: {
    display: 'none', // Effectively remove the header container
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    left: spacing.md,
    zIndex: 101,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlayMuted,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  headerTitle: {
    display: 'none',
  },
  infoButton: {
    position: 'absolute',
    top: 10,
    right: spacing.md,
    zIndex: 101,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlayMuted,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  trackingContainer: {
    flex: 1,
    backgroundColor: scanPalette.neutral,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  focusRing: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    opacity: 0.8,
  },
  topGuide: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  guideText: {
    fontSize: 16,
    fontWeight: '600',
    color: scanPalette.textPrimary,
  },
  guideSubtext: {
    fontSize: 12,
    color: scanPalette.textSecondary,
    marginTop: 4,
  },
  qualityIndicator: {
    width: 100,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 2,
    marginTop: 8,
    overflow: 'hidden',
  },
  qualityBar: {
    width: '100%',
    height: '100%',
    backgroundColor: scanPalette.success,
    borderRadius: 2,
  },
  workoutSelectorContainer: {
    position: 'absolute',
    left: 56, // spacing.md (16) + button width (32) + gap (8)
    zIndex: 60,
  },
  workoutSelectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: scanPalette.overlay,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: scanPalette.border,
    gap: 8,
  },
  workoutSelectorText: {
    fontSize: 14,
    fontWeight: '600',
    color: scanPalette.textPrimary,
  },
  dropdownMenu: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: 8,
    backgroundColor: scanPalette.overlay,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: scanPalette.border,
    padding: 4,
    minWidth: 140,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  dropdownItemText: {
    fontSize: 14,
    color: scanPalette.textPrimary,
  },
  controls: {
    position: 'absolute',
    bottom: 60,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  recordButton: {
    backgroundColor: scanPalette.error,
    borderColor: scanPalette.error,
    minWidth: 160,
  },
  recordButtonActive: {
    backgroundColor: scanPalette.errorDark,
    borderColor: scanPalette.errorDark,
  },
  controlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.accent,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 32,
    gap: 8,
    ...Platform.select({
      web: {
        boxShadow: '0px 4px 8px rgba(76, 140, 255, 0.4)',
      },
      default: {
        shadowColor: scanPalette.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
      },
    }),
  },
  controlButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: scanPalette.textPrimary,
  },
  secondaryButton: {
    marginTop: spacing.sm + spacing.xs,
    backgroundColor: scanPalette.overlay,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  cameraFlipButton: {
    position: 'absolute',
    top: 100,
    right: spacing.md,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 100,
    ...Platform.select({
      web: { boxShadow: '0 2px 6px rgba(0,0,0,0.3)' },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 10,
      },
    }),
  },
  audioToggleButton: {
    position: 'absolute',
    top: 100,
    right: 72,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 100,
    ...Platform.select({
      web: { boxShadow: '0 2px 6px rgba(0,0,0,0.3)' },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 10,
      },
    }),
  },
  audioToggleButtonActive: {
    backgroundColor: scanPalette.textPrimary,
    borderColor: '#7AA9FF',
  },
  zoomControls: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  zoomButton: {
    minWidth: 44,
    height: 44,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    ...Platform.select({
      web: { boxShadow: '0 2px 6px rgba(0,0,0,0.3)' },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 4,
      },
    }),
  },
  zoomButtonLeft: {},
  zoomButtonRight: {},
  zoomButtonText: {
    color: scanPalette.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  statusBadge: {
    position: 'absolute',
    top: 60,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 11,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: scanPalette.textSecondary,
    marginRight: 4,
  },
  statusDotActive: {
    backgroundColor: scanPalette.success,
  },
  statusText: {
    fontSize: 10,
    color: scanPalette.textPrimary,
    fontWeight: '600',
  },
  statusSubtext: {
    fontSize: 8,
    color: scanPalette.textSecondary,
    marginTop: 1,
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  errorText: {
    fontSize: 18,
    color: scanPalette.accentAlt,
    marginTop: spacing.md,
    textAlign: 'center',
  },
  anglesDisplay: {
    position: 'absolute',
    left: spacing.md,
    backgroundColor: scanPalette.overlay,
    borderRadius: borderRadius.lg,
    padding: 8,
    borderWidth: 1,
    borderColor: scanPalette.accentBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    maxWidth: 240,
  },
  anglesTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: scanPalette.textPrimary,
    marginBottom: 4,
  },
  anglesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  angleItem: {
    minWidth: 60,
  },
  angleLabel: {
    fontSize: 9,
    color: scanPalette.textSecondary,
    marginBottom: 1,
  },
  angleValue: {
    fontSize: 14,
    fontWeight: '700',
    color: scanPalette.accent,
  },
  feedbackContainer: {
    position: 'absolute',
    bottom: 120,
    left: spacing.md,
    right: spacing.md,
    backgroundColor: scanPalette.overlay,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  feedbackText: {
    fontSize: 14,
    color: scanPalette.textPrimary,
    marginBottom: 4,
    lineHeight: 20,
  },
});

// Default export to satisfy Expo Router (this file is not a route)
export default null;
