import { useCallback, useEffect, useMemo, useRef } from 'react';
import * as Speech from 'expo-speech';
import { Paths, File as ExpoFile } from 'expo-file-system';
import { Audio, InterruptionModeIOS } from 'expo-av';
import { warnWithTs } from '@/lib/logger';
import { createError, logError } from '@/lib/services/ErrorHandler';
import {
  mapSeverityToAudioHint,
  type CueAudioHint,
} from '@/lib/services/cue-priority-audio';
import type { FaultSeverity } from '@/lib/types/workout-definitions';

// ---------------------------------------------------------------------------
// Cue manifest — maps normalised cue text → MP3 filename.
// Generated by the cue-audio generation script into assets/audio/cues/.
// If the manifest hasn't been generated yet every cue falls back to
// expo-speech, so this is a safe no-op on first build.
// ---------------------------------------------------------------------------

let cueManifest: Record<string, string> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  cueManifest = require('@/assets/audio/cues/cue-manifest.json');
} catch {
  // Manifest not generated yet — all cues fall back to expo-speech
}

// ---------------------------------------------------------------------------
// Sound cache — keeps loaded Audio.Sound instances to avoid reloading
// ---------------------------------------------------------------------------

const soundCache = new Map<string, Audio.Sound>();

const cueAudioDir = new ExpoFile(Paths.document, 'audio/cues/');

async function playCueMp3(filename: string): Promise<boolean> {
  try {
    const file = new ExpoFile(cueAudioDir, filename);
    if (!file.exists) {
      return false;
    }
    const uri = file.uri;

    let sound = soundCache.get(filename);
    if (sound) {
      // Rewind to start so we can replay
      await sound.setPositionAsync(0);
    } else {
      const { sound: newSound } = await Audio.Sound.createAsync({ uri });
      sound = newSound;
      soundCache.set(filename, sound);
    }

    await sound.playAsync();
    return true;
  } catch {
    return false; // fallback to expo-speech
  }
}

async function waitForSoundToFinish(sound: Audio.Sound): Promise<void> {
  return new Promise<void>((resolve) => {
    sound.setOnPlaybackStatusUpdate((status) => {
      if (!status.isLoaded) {
        resolve();
        return;
      }
      if (status.didJustFinish) {
        resolve();
      }
    });
  });
}

async function unloadAllSounds(): Promise<void> {
  const entries = Array.from(soundCache.entries());
  soundCache.clear();
  await Promise.all(
    entries.map(async ([, sound]) => {
      try {
        await sound.unloadAsync();
      } catch {
        // best-effort cleanup
      }
    })
  );
}

// ---------------------------------------------------------------------------
// Public types — deliberately identical to SpeechFeedbackOptions/Controls
// ---------------------------------------------------------------------------

interface PremiumCueAudioOptions {
  enabled: boolean;
  voiceId?: string;
  language?: string;
  rate?: number;
  pitch?: number;
  volume?: number;
  minIntervalMs?: number;
  shouldAllowRecording?: boolean;
  /**
   * Optional severity-based priority hint. When provided, the hook
   * derives `minIntervalMs` + `volume` via the cue-priority-audio
   * mapper instead of using the raw props. Existing callers that
   * omit this keep the previous behavior unchanged.
   *
   * Accepts either:
   *   - a FaultSeverity (1/2/3)
   *   - a partial hint object from mapSeverityToAudioHint()
   */
  priorityHint?: FaultSeverity | Partial<CueAudioHint>;
  onEvent?: (event: {
    cue: string;
    action: 'queued' | 'spoken' | 'dropped';
    reason?: string;
    throttled?: boolean;
    elapsedMs?: number;
  }) => void;
}

interface PremiumCueAudioControls {
  speak: (phrase: string, options?: { immediate?: boolean }) => void;
  stop: () => void;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function usePremiumCueAudio({
  enabled,
  voiceId,
  language = 'en-US',
  rate = 0.55,
  pitch = 1.0,
  volume = 1,
  minIntervalMs = 2000,
  shouldAllowRecording = true,
  priorityHint,
  onEvent,
}: PremiumCueAudioOptions): PremiumCueAudioControls {
  // When a priority hint is supplied, derive interval + volume from the
  // shared mapper so the scan overlay and watch stay in sync.
  const resolved = useMemo(() => {
    if (priorityHint == null) {
      return { minIntervalMs, volume };
    }
    if (typeof priorityHint === 'number') {
      const hint = mapSeverityToAudioHint(priorityHint);
      return {
        minIntervalMs: hint.intervalMs,
        volume: hint.volume,
      };
    }
    return {
      minIntervalMs: priorityHint.intervalMs ?? minIntervalMs,
      volume: priorityHint.volume ?? volume,
    };
  }, [priorityHint, minIntervalMs, volume]);
  const effectiveInterval = resolved.minIntervalMs;
  const effectiveVolume = resolved.volume;
  const queueRef = useRef<string[]>([]);
  const isSpeakingRef = useRef(false);
  const lastPhraseRef = useRef<string | null>(null);
  const lastTimestampRef = useRef(0);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  const audioConfiguredRef = useRef(false);
  const activeSoundRef = useRef<Audio.Sound | null>(null);

  // ---- Error helper ----

  const reportAsyncError = useCallback((code: string, message: string, error: unknown) => {
    logError(
      createError('unknown', code, message, {
        details: error,
        severity: 'warning',
        retryable: true,
      }),
      {
        feature: 'app',
        location: 'hooks/use-premium-cue-audio',
      }
    );
  }, []);

  // ---- Audio mode ----

  const ensureAudioMode = useCallback(async () => {
    if (audioConfiguredRef.current) {
      return;
    }
    try {
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: shouldAllowRecording,
        staysActiveInBackground: true,
        playsInSilentModeIOS: true,
        interruptionModeIOS: InterruptionModeIOS.MixWithOthers,
        shouldDuckAndroid: false,
        playThroughEarpieceAndroid: false,
      });
      audioConfiguredRef.current = true;
    } catch (error) {
      audioConfiguredRef.current = false;
      if (__DEV__) {
        warnWithTs('[PremiumCueAudio] Failed to set audio mode', error);
      }
    }
  }, [shouldAllowRecording]);

  // Reset audio config when recording requirement changes
  useEffect(() => {
    audioConfiguredRef.current = false;
    ensureAudioMode().catch((error) => {
      reportAsyncError('PREMIUM_AUDIO_RECONFIG_FAILED', 'Failed to reconfigure premium audio mode', error);
    });
  }, [ensureAudioMode, reportAsyncError]);

  // ---- Timeout helper ----

  const clearPendingTimeout = useCallback(() => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
  }, []);

  // ---- Core playback: MP3 → expo-speech fallback ----

  const playCue = useCallback(
    async (text: string): Promise<void> => {
      const manifestKey = text.toLowerCase().trim();
      const filename = cueManifest[manifestKey];

      if (filename) {
        const played = await playCueMp3(filename);
        if (played) {
          // Track active sound for stop()
          activeSoundRef.current = soundCache.get(filename) ?? null;
          const sound = activeSoundRef.current;
          if (sound) {
            await waitForSoundToFinish(sound);
          }
          activeSoundRef.current = null;
          return;
        }
        // MP3 failed — fall through to expo-speech
        if (__DEV__) {
          warnWithTs(`[PremiumCueAudio] MP3 playback failed for "${text}", falling back to expo-speech`);
        }
      }

      // Fallback: expo-speech
      return new Promise<void>((resolve) => {
        Speech.speak(text, {
          voice: voiceId,
          language,
          rate,
          pitch,
          volume: effectiveVolume,
          onDone: resolve,
          onStopped: resolve,
          onError: () => resolve(),
        });
      });
    },
    [voiceId, language, rate, pitch, effectiveVolume]
  );

  // ---- Queue flusher (matches useSpeechFeedback logic exactly) ----

  const flushQueue = useCallback(async () => {
    if (!enabled) {
      queueRef.current = [];
      lastPhraseRef.current = null;
      clearPendingTimeout();
      if (isSpeakingRef.current) {
        Speech.stop();
        const activeSound = activeSoundRef.current;
        if (activeSound) {
          try {
            await activeSound.stopAsync();
          } catch {
            // best-effort
          }
          activeSoundRef.current = null;
        }
        isSpeakingRef.current = false;
      }
      return;
    }

    if (isSpeakingRef.current) {
      return;
    }

    const now = Date.now();
    const elapsed = now - lastTimestampRef.current;

    if (elapsed < effectiveInterval) {
      clearPendingTimeout();
      if (queueRef.current[0]) {
        onEvent?.({
          cue: queueRef.current[0],
          action: 'dropped',
          reason: 'throttled_interval',
          throttled: true,
          elapsedMs: elapsed,
        });
      }
      timeoutRef.current = setTimeout(() => {
        flushQueue().catch((error) => {
          reportAsyncError(
            'PREMIUM_AUDIO_FLUSH_RETRY_FAILED',
            'Failed to flush premium audio queue after throttle delay',
            error
          );
        });
      }, effectiveInterval - elapsed);
      return;
    }

    const next = queueRef.current.shift();
    if (!next) {
      return;
    }

    try {
      await ensureAudioMode();
    } catch (error) {
      isSpeakingRef.current = false;
      reportAsyncError('PREMIUM_AUDIO_MODE_FAILED', 'Audio mode configuration failed, skipping cue', error);
      onEvent?.({ cue: next, action: 'dropped', reason: 'audio_mode_error' });
      return;
    }

    isSpeakingRef.current = true;
    lastPhraseRef.current = next;
    lastTimestampRef.current = now;
    onEvent?.({ cue: next, action: 'spoken' });

    try {
      await playCue(next);
    } catch (error) {
      onEvent?.({ cue: next, action: 'dropped', reason: 'playback_error' });
      reportAsyncError('PREMIUM_AUDIO_PLAYBACK_FAILED', 'Premium cue playback failed', error);
    } finally {
      isSpeakingRef.current = false;
      flushQueue().catch((error) => {
        reportAsyncError(
          'PREMIUM_AUDIO_FLUSH_ON_DONE_FAILED',
          'Failed to flush premium audio queue after completion',
          error
        );
      });
    }
  }, [enabled, effectiveInterval, clearPendingTimeout, ensureAudioMode, playCue, onEvent, reportAsyncError]);

  // ---- Public speak() ----

  const speak = useCallback(
    (phrase: string, options?: { immediate?: boolean }) => {
      const text = phrase?.trim();
      if (!text) {
        return;
      }

      if (!enabled) {
        onEvent?.({ cue: text, action: 'dropped', reason: 'disabled' });
        return;
      }

      const now = Date.now();
      const lastPhrase = lastPhraseRef.current;
      if (lastPhrase === text && now - lastTimestampRef.current < effectiveInterval) {
        onEvent?.({
          cue: text,
          action: 'dropped',
          reason: 'throttled_same_cue',
          throttled: true,
          elapsedMs: now - lastTimestampRef.current,
        });
        return;
      }

      const queue = queueRef.current;
      if (!options?.immediate && queue[queue.length - 1] === text) {
        onEvent?.({ cue: text, action: 'dropped', reason: 'duplicate_in_queue' });
        return;
      }

      if (options?.immediate) {
        queue.unshift(text);
      } else {
        queue.push(text);
      }
      onEvent?.({ cue: text, action: 'queued' });

      flushQueue().catch((error) => {
        reportAsyncError('PREMIUM_AUDIO_FLUSH_ENQUEUE_FAILED', 'Failed to flush premium audio queue after enqueue', error);
      });
    },
    [enabled, flushQueue, effectiveInterval, onEvent, reportAsyncError]
  );

  // ---- Public stop() ----

  const stop = useCallback(() => {
    queueRef.current = [];
    clearPendingTimeout();
    Speech.stop();
    const activeSound = activeSoundRef.current;
    if (activeSound) {
      activeSound.stopAsync().catch(() => {
        // best-effort stop
      });
      activeSoundRef.current = null;
    }
    isSpeakingRef.current = false;
  }, [clearPendingTimeout]);

  // ---- Lifecycle ----

  useEffect(() => {
    if (!enabled) {
      stop();
    } else {
      ensureAudioMode().catch((error) => {
        reportAsyncError('PREMIUM_AUDIO_MODE_INIT_FAILED', 'Failed to initialize premium audio mode', error);
      });
      flushQueue().catch((error) => {
        reportAsyncError('PREMIUM_AUDIO_FLUSH_INIT_FAILED', 'Failed to initialize premium audio queue processing', error);
      });
    }

    return () => {
      stop();
    };
  }, [enabled, flushQueue, stop, ensureAudioMode, reportAsyncError]);

  // Cleanup all cached sounds on unmount
  useEffect(() => {
    return () => {
      unloadAllSounds().catch(() => {
        // best-effort unmount cleanup
      });
    };
  }, []);

  return { speak, stop };
}
