import { Platform, StyleSheet } from 'react-native';
import { spacing, borderRadius } from '@/design-system/theme';
import { tabColors } from './tab-theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tabColors.background,
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: tabColors.background,
  },
  loadingText: {
    marginTop: spacing.md,
    fontSize: 16,
    color: tabColors.textSecondary,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  list: {
    padding: spacing.md,
    paddingBottom: 100,
  },
  cardWrapper: {
    marginBottom: spacing.sm + spacing.xs,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  cardGradient: {
    borderRadius: borderRadius.lg,
    padding: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: tabColors.border,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  swipeDelete: {
    backgroundColor: tabColors.error,
    justifyContent: 'center',
    alignItems: 'center',
    width: 88,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.sm + spacing.xs,
    flexDirection: 'column',
  },
  swipeDeleteText: {
    color: '#fff',
    fontSize: 12,
    marginTop: spacing.xs,
    fontWeight: '600',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: tabColors.textPrimary,
    flex: 1,
    marginRight: spacing.sm + spacing.xs,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  cardDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardDate: {
    fontSize: 14,
    color: tabColors.textSecondary,
    marginLeft: spacing.xs,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  cardDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  detailItem: {
    alignItems: 'center',
    minWidth: 60,
  },
  detailValue: {
    fontSize: 24,
    fontWeight: '700',
    color: tabColors.accent,
    marginBottom: 2,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  detailLabel: {
    fontSize: 12,
    color: tabColors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  cardFooter: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: tabColors.border,
    paddingTop: 12,
    marginTop: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  actionText: {
    color: tabColors.accent,
    fontSize: 14,
    fontWeight: '500',
    marginLeft: spacing.xs + 2,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  divider: {
    width: 1,
    backgroundColor: tabColors.border,
    marginVertical: 4,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: tabColors.background,
  },
  emptyIllustration: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(76, 140, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: tabColors.textPrimary,
    marginBottom: spacing.sm,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  emptyDescription: {
    fontSize: 16,
    color: tabColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.lg,
    lineHeight: 24,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  addFirstButton: {
    backgroundColor: tabColors.accent,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + spacing.xs,
    borderRadius: borderRadius.md,
    shadowColor: tabColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  addFirstButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif-medium',
  },
  addButton: {
    position: 'absolute',
    right: spacing.lg,
    bottom: 100,
    backgroundColor: tabColors.accent,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: tabColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
});
