import { Platform, StyleSheet } from 'react-native';
import { spacing, borderRadius } from '@/design-system/theme';
import { tabColors } from './tab-theme';

export const scanPalette = tabColors;

export const styles = StyleSheet.create({
  fullFill: StyleSheet.absoluteFillObject,
  container: {
    flex: 1,
    backgroundColor: scanPalette.background,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    zIndex: 50,
    backgroundColor: scanPalette.overlayHeader,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingTop: 0,
  },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlayMuted,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: scanPalette.textPrimary,
  },
  infoButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlayMuted,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  trackingContainer: {
    flex: 1,
    backgroundColor: scanPalette.neutral,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  focusRing: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    opacity: 0.8,
  },
  topGuide: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  guideText: {
    fontSize: 16,
    fontWeight: '600',
    color: scanPalette.textPrimary,
  },
  guideSubtext: {
    fontSize: 12,
    color: scanPalette.textSecondary,
    marginTop: 4,
  },
  qualityIndicator: {
    width: 100,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 2,
    marginTop: 8,
    overflow: 'hidden',
  },
  qualityBar: {
    width: '100%',
    height: '100%',
    backgroundColor: scanPalette.success,
    borderRadius: 2,
  },
  controls: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    gap: 20,
    zIndex: 10,
  },
  zoomControls: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  zoomButton: {
    minWidth: 44,
    height: 44,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    ...Platform.select({
      web: { boxShadow: '0 2px 6px rgba(0,0,0,0.3)' },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 4,
      },
    }),
  },
  zoomButtonLeft: {},
  zoomButtonRight: {},
  zoomButtonText: {
    color: scanPalette.textPrimary,
    fontSize: 20,
    fontWeight: '700',
  },
  controlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.accent,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 28,
    gap: 12,
    ...Platform.select({
      web: {
        boxShadow: '0px 4px 8px rgba(76, 140, 255, 0.4)',
      },
      default: {
        shadowColor: scanPalette.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
      },
    }),
  },
  controlButtonSmall: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
    gap: 8,
  },
  stopButton: {
    backgroundColor: scanPalette.accentAlt,
    ...Platform.select({
      web: {
        boxShadow: '0px 4px 8px rgba(255, 107, 107, 0.4)',
      },
      default: {
        shadowColor: scanPalette.accentAlt,
      },
    }),
  },
  secondaryButton: {
    marginTop: spacing.sm + spacing.xs,
    backgroundColor: scanPalette.overlay,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  cameraFlipButton: {
    position: 'absolute',
    top: 120,
    right: spacing.md,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 100,
    ...Platform.select({
      web: {
        boxShadow: '0 2px 6px rgba(0,0,0,0.3)',
      },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 10,
      },
    }),
  },
  audioToggleButton: {
    position: 'absolute',
    top: 120,
    right: 72,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 100,
    ...Platform.select({
      web: {
        boxShadow: '0 2px 6px rgba(0,0,0,0.3)',
      },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 10,
      },
    }),
  },
  audioToggleButtonActive: {
    backgroundColor: scanPalette.textPrimary,
    borderColor: '#7AA9FF',
  },
  controlButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: scanPalette.textPrimary,
  },
  statusBadge: {
    position: 'absolute',
    top: 100,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: scanPalette.overlay,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: scanPalette.border,
    zIndex: 11,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: scanPalette.textSecondary,
    marginRight: 6,
  },
  statusDotActive: {
    backgroundColor: scanPalette.success,
  },
  statusText: {
    fontSize: 12,
    color: scanPalette.textPrimary,
    fontWeight: '600',
  },
  statusSubtext: {
    fontSize: 10,
    color: scanPalette.textSecondary,
    marginTop: 2,
  },
  modeToggle: {
    position: 'absolute',
    left: spacing.md,
    flexDirection: 'row',
    gap: spacing.sm,
    zIndex: 20,
  },
  modeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: scanPalette.border,
    backgroundColor: scanPalette.overlaySubtle,
  },
  modeChipActive: {
    backgroundColor: scanPalette.accent,
    borderColor: scanPalette.accent,
  },
  modeChipText: {
    color: scanPalette.textSecondary,
    fontWeight: '600',
  },
  modeChipTextActive: {
    color: '#0B1F3A',
  },
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  errorText: {
    fontSize: 18,
    color: scanPalette.accentAlt,
    marginTop: spacing.md,
    textAlign: 'center',
  },
  anglesDisplay: {
    position: 'absolute',
    left: spacing.md,
    backgroundColor: scanPalette.overlay,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: scanPalette.accentBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    maxWidth: 280,
  },
  anglesTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: scanPalette.textPrimary,
    marginBottom: spacing.sm,
  },
  anglesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  metricsUploadHint: {
    marginTop: 10,
    padding: spacing.sm,
    borderRadius: 10,
    backgroundColor: scanPalette.accentSurface,
    borderWidth: 1,
    borderColor: scanPalette.accentSurfaceBorder,
  },
  metricsUploadLabel: {
    fontSize: 12,
    color: scanPalette.textSecondary,
    marginBottom: 4,
  },
  metricsUploadValue: {
    fontSize: 13,
    color: scanPalette.textPrimary,
    fontWeight: '700',
  },
  metricsUploadSubtext: {
    fontSize: 11,
    color: scanPalette.textSecondary,
    marginTop: 2,
  },
  uploadButton: {
    marginTop: spacing.sm + 2,
    backgroundColor: scanPalette.accent,
    borderRadius: borderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  uploadButtonDisabled: {
    opacity: 0.7,
  },
  uploadButtonText: {
    color: '#0B1F3A',
    fontWeight: '700',
  },
  recordButton: {
    backgroundColor: scanPalette.error,
    borderColor: scanPalette.error,
  },
  recordButtonActive: {
    backgroundColor: scanPalette.errorDark,
    borderColor: scanPalette.errorDark,
  },
  angleItem: {
    minWidth: 80,
  },
  angleLabel: {
    fontSize: 10,
    color: scanPalette.textSecondary,
    marginBottom: 2,
  },
  angleValue: {
    fontSize: 16,
    fontWeight: '700',
    color: scanPalette.accent,
  },
  feedbackContainer: {
    position: 'absolute',
    bottom: 120,
    left: spacing.md,
    right: spacing.md,
    backgroundColor: scanPalette.overlay,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: scanPalette.border,
  },
  feedbackText: {
    fontSize: 14,
    color: scanPalette.textPrimary,
    marginBottom: 4,
    lineHeight: 20,
  },
});
