import { StyleSheet } from 'react-native';
import { spacing, borderRadius } from './_theme-constants';
import { tabColors } from './_tab-theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tabColors.background,
    padding: spacing.lg,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: tabColors.textPrimary,
    marginTop: spacing.md,
  },
  subtitle: {
    fontSize: 16,
    color: tabColors.textSecondary,
    marginTop: spacing.sm,
  },
  content: {
    flex: 1,
    marginTop: spacing.xl,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  coachEmojiButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coachEmojiText: {
    fontSize: 18,
  },
  feedTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  feedTopLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  feedTopAvatarWrap: {
    position: 'relative',
  },
  feedTopAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(76, 140, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedTopAvatarText: {
    color: tabColors.textPrimary,
    fontWeight: '700',
  },
  feedTopStatus: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#3CD77D',
    borderWidth: 2,
    borderColor: tabColors.background,
    right: -1,
    bottom: -1,
  },
  feedTopTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: tabColors.textPrimary,
  },
  newPostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    backgroundColor: 'rgba(76, 140, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(76, 140, 255, 0.35)',
  },
  feedTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  newPostText: {
    color: '#DDE6FF',
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  headerTextContainer: {
    flex: 1,
  },
  tabSwitcher: {
    flexDirection: 'row',
    backgroundColor: '#0A172A',
    borderRadius: 14,
    padding: spacing.xs,
    marginTop: spacing.md,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(76, 140, 255, 0.15)',
  },
  tabText: {
    color: tabColors.textSecondary,
    fontWeight: '600',
  },
  tabTextActive: {
    color: tabColors.textPrimary,
  },
  coachContainer: {
    flex: 1,
    marginTop: spacing.xl,
  },
  quickPrompts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  quickPrompt: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.xl,
    backgroundColor: tabColors.accentSurface,
    borderWidth: 1,
    borderColor: tabColors.accentSurfaceBorder,
  },
  quickPromptText: {
    color: tabColors.textPrimary,
    fontWeight: '600',
  },
  coachError: {
    borderWidth: 1,
    borderColor: tabColors.errorDark,
    backgroundColor: '#2A0C0C',
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.md,
  },
  coachErrorTitle: {
    color: tabColors.textPrimary,
    marginBottom: spacing.xs,
    fontWeight: '600',
  },
  coachErrorText: {
    color: tabColors.textSecondary,
  },
  coachList: {
    flex: 1,
  },
  coachListContent: {
    paddingBottom: spacing.xl,
  },
  coachBubbleRow: {
    marginBottom: spacing.md,
  },
  coachBubble: {
    maxWidth: '85%',
    padding: spacing.md,
    borderRadius: borderRadius.xl,
    borderWidth: 1,
  },
  coachBubbleAssistant: {
    backgroundColor: tabColors.overlay,
    borderColor: tabColors.accentBorder,
  },
  coachBubbleUser: {
    backgroundColor: '#0C2A4A',
    borderColor: tabColors.accent,
    marginLeft: 'auto',
  },
  coachBubbleText: {
    color: tabColors.textPrimary,
    lineHeight: 20,
  },
  coachBubbleMeta: {
    color: tabColors.textSecondary,
    fontSize: 12,
    marginTop: spacing.xs,
  },
  coachComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: '#0A172A',
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: tabColors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.md,
  },
  coachInput: {
    flex: 1,
    color: tabColors.textPrimary,
    paddingVertical: spacing.sm,
  },
  coachSend: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tabColors.accent,
  },
  coachSendDisabled: {
    backgroundColor: tabColors.accentSurfaceBorder,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: tabColors.textPrimary,
    marginBottom: spacing.md,
  },
  actionGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  actionCardWrapper: {
    flex: 1,
  },
  actionCard: {
    borderRadius: borderRadius.xl,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tabColors.border,
  },
  actionIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(76, 140, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.sm + spacing.xs,
  },
  actionIconText: {
    fontSize: 24,
  },
  actionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: tabColors.textPrimary,
    marginBottom: 4,
  },
  actionSubtitle: {
    fontSize: 14,
    color: tabColors.textSecondary,
    textAlign: 'center',
  },
  statsSection: {
    marginTop: spacing.sm,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  statCard: {
    flex: 1,
    borderRadius: borderRadius.xl,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tabColors.border,
  },
  statNumber: {
    fontSize: 32,
    fontWeight: 'bold',
    color: tabColors.accent,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 14,
    color: tabColors.textSecondary,
    textAlign: 'center',
  },
  feedContainer: {
    flex: 1,
    marginTop: spacing.md,
    marginHorizontal: -spacing.lg,
  },
  feedListContent: {
    paddingBottom: 120,
    gap: spacing.md,
    paddingHorizontal: spacing.md,
  },
  feedMeta: {
    color: tabColors.textSecondary,
    fontSize: 12,
  },
  feedCard: {
    backgroundColor: '#0B1324',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: spacing.md,
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  postHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  postHeaderText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  postAvatarWrap: {
    position: 'relative',
  },
  postAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(76, 140, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  postAvatarText: {
    color: tabColors.textPrimary,
    fontWeight: '700',
  },
  postAvatarStatus: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#3CD77D',
    borderWidth: 2,
    borderColor: '#0B1324',
    right: -1,
    bottom: -1,
  },
  postName: {
    color: tabColors.textPrimary,
    fontWeight: '700',
    fontSize: 16,
    flexShrink: 1,
  },
  postMeta: {
    color: tabColors.textSecondary,
    fontSize: 12,
    flexShrink: 1,
  },
  postMoreButton: {
    padding: spacing.xs,
    marginLeft: spacing.xs,
  },
  postText: {
    color: tabColors.textPrimary,
    fontSize: 15,
    marginBottom: spacing.sm,
  },
  videoWrapper: {
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    position: 'relative',
  },
  video: {
    width: '100%',
    height: 320,
    backgroundColor: tabColors.background,
    position: 'relative',
  },
  videoSurface: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  videoPoster: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  videoTapSurface: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
  },
  playButton: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#7FB3FF',
    alignItems: 'center',
    justifyContent: 'center',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -28 }, { translateY: -28 }],
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    zIndex: 3,
  },
  videoPlaceholder: {
    height: 320,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(76, 140, 255, 0.05)',
  },
  videoPlaceholderText: {
    color: tabColors.textSecondary,
    fontSize: 14,
  },
  formScoreBadge: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    backgroundColor: '#F2D675',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(10, 15, 28, 0.25)',
    zIndex: 2,
    elevation: 2,
  },
  formScoreText: {
    color: '#0A0F1C',
    fontSize: 14,
    fontWeight: '700',
  },
  videoOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    zIndex: 2,
  },
  videoOverlayMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  videoOverlaySummary: {
    color: '#F5F1DE',
    fontSize: 15,
    fontWeight: '600',
  },
  videoOverlayTime: {
    color: '#CBD6F0',
    fontSize: 12,
  },
  videoControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  videoProgressTrack: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(127, 179, 255, 0.35)',
    overflow: 'hidden',
  },
  videoProgressFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#7FB3FF',
  },
  videoTimecode: {
    color: '#DDE6FF',
    fontSize: 11,
    fontWeight: '600',
    minWidth: 68,
    textAlign: 'right',
  },
  muteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(127, 179, 255, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(127, 179, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullscreenButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(127, 179, 255, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(127, 179, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  engagementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    marginTop: spacing.sm,
  },
  engagementGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  engagementText: {
    color: '#CBD6F0',
    fontSize: 13,
  },
  engagementTextActive: {
    color: '#FF6B6B',
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  statText: {
    color: tabColors.textPrimary,
    fontSize: 13,
    flexShrink: 1,
  },
  feedLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg + spacing.sm,
  },
  feedEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.sm,
  },
  errorText: {
    color: tabColors.accentAlt,
    marginBottom: spacing.sm,
  },
  uploadButton: {
    marginTop: spacing.md,
    backgroundColor: tabColors.accent,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
  },
  uploadButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  coachWelcome: {
    backgroundColor: '#0C1E36',
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: '#4C8CFF',
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  coachWelcomeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  coachWelcomeClose: {
    padding: spacing.xs,
    marginRight: spacing.xs,
  },
  coachWelcomeTitleContainer: {
    flex: 1,
    paddingLeft: spacing.xs,
  },
  coachWelcomeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: tabColors.textPrimary,
    marginBottom: spacing.xs,
  },
  coachWelcomeButton: {
    backgroundColor: tabColors.accent,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    alignSelf: 'flex-start',
    marginTop: spacing.sm,
  },
  coachWelcomeText: {
    fontSize: 14,
    color: tabColors.textSecondary,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  coachWelcomeButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  coachWelcomeExampleContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: borderRadius.md,
    padding: spacing.sm,
    marginTop: spacing.xs,
  },
  coachWelcomeExample: {
    fontSize: 13,
    color: tabColors.textSecondary,
    lineHeight: 18,
  },
});

// Default export to satisfy Expo Router (this file is not a route)
export default null;
